### ISSUE TITLE
irb error: cannot load such file -- pry

### ISSUE THREAD

**Issue by vol1ura** [davidcelis/rack-console#4]
In production environment I have no `pry` and in case of any exception I get also LoadError from rack console:

```
irb(main):001:0> raise
<internal:/usr/local/rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- pry (LoadError)
Did you mean?  pty                                            
        from <internal:/usr/local/rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /home/demo/myapp/shared/bundle/ruby/3.2.0/gems/rack-console-1.3.1/lib/rack/console.rb:33:in `start'
```

This error appeared after updating to Ruby 3.2.2. On Ruby 2.7 all was ok. This is most likely due to the irb update in new ruby.

**Comment by vol1ura** [comment]
@davidcelis hello, can u help with this?

**Comment by davidcelis** [comment]
@vol1ura When testing this out, I got both the original exception and the additional `LoadError`. To be clear, this wasn't _swallowing_ exceptions, was it? Just printing an additional one?

Either way, I've pushed a new version (v1.4.1) which should fix this

**Comment by vol1ura** [comment]
Yes, there is additional error `LoadError`

Thank you for answer

**Comment by vol1ura** [comment]
@davidcelis can you please also make a path-release for 1.3 version (rack 2)?

**Comment by davidcelis** [comment]
Sure, just pushed up v1.3.2
